"""MCP tool routes: document ingestion, search, and Q&A.

Run via main.py at the project root, which calls `serve()` below.
"""

import os
import json
import asyncio

import anthropic
from dotenv import load_dotenv
from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp import types

from src.ingestion import loader
from src.llm import llm_client
from src.retrieval import retriever
from src.utils import helpers
from src.vectordb import vector_store

load_dotenv()

app = Server("rag-server")

_claude_client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])


@app.list_tools()
async def list_tools() -> list[types.Tool]:
    return [
        types.Tool(
            name="ingest_document",
            description=(
                "Download and index a document from a Google Drive URL. "
                "Supports PDF, DOCX, TXT, MD, and PNG/image files."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "url": {
                        "type": "string",
                        "description": "Public Google Drive share URL of the document",
                    }
                },
                "required": ["url"],
            },
        ),
        types.Tool(
            name="search_documents",
            description="Semantically search indexed documents and return the most relevant chunks.",
            inputSchema={
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "Search query in natural language",
                    },
                    "n_results": {
                        "type": "integer",
                        "description": "Number of results to return (default: 5)",
                        "default": 5,
                    },
                },
                "required": ["query"],
            },
        ),
        types.Tool(
            name="ask_question",
            description=(
                "Ask a question and get an answer generated by Claude "
                "using the indexed documents as context (full RAG pipeline)."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "question": {
                        "type": "string",
                        "description": "The question to answer",
                    },
                    "n_context_chunks": {
                        "type": "integer",
                        "description": "Number of context chunks to retrieve (default: 5)",
                        "default": 5,
                    },
                },
                "required": ["question"],
            },
        ),
        types.Tool(
            name="list_documents",
            description="List all documents currently indexed in the knowledge base.",
            inputSchema={"type": "object", "properties": {}},
        ),
        types.Tool(
            name="delete_document",
            description="Remove a document and all its chunks from the knowledge base by its source URL.",
            inputSchema={
                "type": "object",
                "properties": {
                    "source_url": {
                        "type": "string",
                        "description": "The Google Drive URL used when the document was ingested",
                    }
                },
                "required": ["source_url"],
            },
        ),
    ]


@app.call_tool()
async def call_tool(name: str, arguments: dict) -> list[types.TextContent]:
    try:
        if name == "ingest_document":
            url = arguments["url"]
            chunks, chunk_metadatas, summary = await asyncio.get_event_loop().run_in_executor(
                None, loader.load_document, url, _claude_client
            )
            count = vector_store.add_chunks(chunks, chunk_metadatas)
            result = {
                "status": "success",
                "filename": summary["filename"],
                "doc_type": summary["doc_type"],
                "chunks_indexed": count,
                "file_count": summary.get("file_count", 1),
                "skipped_files": summary.get("skipped_files", []),
            }
            if summary.get("doc_type") == "folder":
                result["processed_files"] = summary.get("processed_files", [])

        elif name == "search_documents":
            query = arguments["query"]
            n = arguments.get("n_results", helpers.get("retrieval", "n_results"))
            hits = retriever.retrieve(query, n_results=n)
            result = {
                "query": query,
                "results": [
                    {
                        "text": h["text"][:400] + ("..." if len(h["text"]) > 400 else ""),
                        "score": h["score"],
                        "source": h["metadata"].get("filename", "unknown"),
                    }
                    for h in hits
                ],
                "total_found": len(hits),
            }

        elif name == "ask_question":
            question = arguments["question"]
            n = arguments.get("n_context_chunks", helpers.get("retrieval", "n_context_chunks"))
            hits = retriever.retrieve_context(question, n_chunks=n)
            response = await asyncio.get_event_loop().run_in_executor(
                None, llm_client.answer, question, hits, _claude_client
            )
            result = response

        elif name == "list_documents":
            docs = vector_store.list_documents()
            result = {"documents": docs, "total": len(docs)}

        elif name == "delete_document":
            source_url = arguments["source_url"]
            deleted = vector_store.delete_document(source_url)
            result = {"deleted_chunks": deleted, "source_url": source_url}

        else:
            result = {"error": f"Unknown tool: {name}"}

    except Exception as e:
        result = {"error": str(e)}

    return [types.TextContent(type="text", text=json.dumps(result, indent=2))]


@app.list_resources()
async def list_resources() -> list[types.Resource]:
    docs = vector_store.list_documents()
    return [
        types.Resource(
            uri=f"rag://documents/{i}",
            name=doc["filename"],
            description=f"{doc['doc_type'].upper()} — {doc['source_url']}",
            mimeType="text/plain",
        )
        for i, doc in enumerate(docs)
    ]


async def serve() -> None:
    """Run the MCP server over stdio. Invoked by main.py."""
    async with stdio_server() as (read_stream, write_stream):
        await app.run(read_stream, write_stream, app.create_initialization_options())
